/*
    Account detail helper, step 2 of 3. Run step 010 first.
    TextSeed.xlsx is the authoritative source for all four category lists
    and account defaults. Its IDs 31 and 313 (accounts 693, 694, 697) have
    no corresponding text in any category and are left without defaults.
    The auditor's spelling, spacing, and wording are preserved verbatim.
*/
USE [AuditAddIn];
GO

IF OBJECT_ID(N'Settings.Users', N'U') IS NULL
    THROW 53200, 'Run step 010 before step 020.', 1;
GO

IF OBJECT_ID(N'Settings.TextCategories', N'U') IS NULL
BEGIN
    CREATE TABLE [Settings].[TextCategories]
    (
        [Code] varchar(50) NOT NULL CONSTRAINT [PK_Settings_TextCategories] PRIMARY KEY,
        [DisplayNameSk] nvarchar(100) NOT NULL,
        [SortOrder] tinyint NOT NULL CONSTRAINT [UQ_Settings_TextCategories_Order] UNIQUE
    );
END;
GO

IF OBJECT_ID(N'Settings.PredefinedTexts', N'U') IS NULL
BEGIN
    CREATE TABLE [Settings].[PredefinedTexts]
    (
        [UserId] int NOT NULL,
        [CategoryCode] varchar(50) NOT NULL,
        [TextId] int NOT NULL,
        [TextSk] nvarchar(500) NOT NULL,
        [SortOrder] int NOT NULL,
        [IsActive] bit NOT NULL CONSTRAINT [DF_Settings_PredefinedTexts_IsActive] DEFAULT (1),
        CONSTRAINT [PK_Settings_PredefinedTexts] PRIMARY KEY ([UserId], [CategoryCode], [TextId]),
        CONSTRAINT [FK_Settings_PredefinedTexts_User] FOREIGN KEY ([UserId]) REFERENCES [Settings].[Users] ([Id]),
        CONSTRAINT [FK_Settings_PredefinedTexts_Category] FOREIGN KEY ([CategoryCode]) REFERENCES [Settings].[TextCategories] ([Code]),
        CONSTRAINT [CK_Settings_PredefinedTexts_Text] CHECK (LEN(TRIM([TextSk])) > 0),
        CONSTRAINT [CK_Settings_PredefinedTexts_Order] CHECK ([SortOrder] > 0)
    );
END;
GO

IF OBJECT_ID(N'Settings.PredefinedTextMappings', N'U') IS NULL
BEGIN
    CREATE TABLE [Settings].[PredefinedTextMappings]
    (
        [UserId] int NOT NULL,
        [CategoryCode] varchar(50) NOT NULL,
        [Account] varchar(3) NOT NULL,
        [TextId] int NOT NULL,
        CONSTRAINT [PK_Settings_PredefinedTextMappings] PRIMARY KEY ([UserId], [CategoryCode], [Account]),
        CONSTRAINT [FK_Settings_PredefinedTextMappings_Text] FOREIGN KEY ([UserId], [CategoryCode], [TextId])
            REFERENCES [Settings].[PredefinedTexts] ([UserId], [CategoryCode], [TextId]),
        CONSTRAINT [CK_Settings_PredefinedTextMappings_Account] CHECK
            (LEN([Account]) = 3 AND [Account] NOT LIKE '%[^0-9]%')
    );
END;
GO

DECLARE @Categories table ([Code] varchar(50), [DisplayNameSk] nvarchar(100), [SortOrder] tinyint);
INSERT @Categories VALUES
    ('Valuation', N'Ocenenie', 1),
    ('ExistenceAndOwnership', N'Existencia, vlastníctvo', 2),
    ('CompletenessOfAccounting', N'Úplnosť, účtovanie', 3),
    ('AccuratePeriodDetermination', N'Správnosť určenia obdobia', 4);
INSERT [Settings].[TextCategories] ([Code], [DisplayNameSk], [SortOrder])
SELECT s.[Code], s.[DisplayNameSk], s.[SortOrder] FROM @Categories AS s
WHERE NOT EXISTS (SELECT 1 FROM [Settings].[TextCategories] AS c WHERE c.[Code] = s.[Code]);

DECLARE @Texts table ([CategoryCode] varchar(50), [TextId] int, [TextSk] nvarchar(500));
INSERT @Texts VALUES
    ('Valuation', 1, N'zostaková hodnota je zhodná s pomocnou evidenciou'),
    ('Valuation', 2, N'zostaková hodnota oprávok je zhodná s pomocnou evidenciou'),
    ('Valuation', 3, N'zostaková hodnota opravných položiek zhodná s pomocnou evidenciou'),
    ('Valuation', 4, N'zostaková hodnota zásob je zhodná s pomocnou evidenciou'),
    ('Valuation', 5, N'zostaková hodnota finančných prostriedkov je zhodná s pomocnou evidenciou'),
    ('Valuation', 6, N'zostaková hodnota pohľadávok je zhodná s pomocnou evidenciou - dcom '),
    ('Valuation', 7, N'zostaková hodnota záväzkov je zhodná s inventarizovaným zostatkom, nedoplatky hradené v lehote splatnosti v nasledujúcom období'),
    ('Valuation', 8, N'zostaková hodnota rezerv je zhodná s inventarizovaným zostatkom, prípadné zmeny budú vykonané  na základe výsledkov konaní'),
    ('Valuation', 9, N'zostaková hodnota časového rozlíšenia je zhodná s inventarizovaným zostatkom,  - inventarizácia podložená príslušnými dokladmi'),
    ('Valuation', 10, N'zostaková hodnota nevysporiadaného výsledku hospodárenia je zhodná s inventarizovaným zostatkom,  - bez vykonaných významných opráv v priebehu účtovného obodbia'),
    ('Valuation', 11, N'zostaková hodnota úveru je zhodná s inventarizovaným zostatkom,  - inventarizácia podložená príslušnými doklami (bankové výpisy), poskytnutá banková konfirmácia - bez rozdielov'),
    ('Valuation', 12, N'náklady účtované v nominálnej hodnote, odzrkadľujú ekonomickú aktivitu účtovnej jednotky '),
    ('Valuation', 13, N'výnosy účtované v súlade s ekonomickou aktivitou  - výnos podľa ekonomickej aktivity - kontrola na rozpočet '),
    ('ExistenceAndOwnership', 1, N'majetok je vlastnený účtovnou jendotkou '),
    ('ExistenceAndOwnership', 2, N'oprávky k majetku, ktorý je vlastnený účtovnou jendotkou '),
    ('ExistenceAndOwnership', 3, N'opravná položka k majetku, ktorý je vlastnený účtovnou jendotkou '),
    ('ExistenceAndOwnership', 4, N'zásoby sú vlastnené účtovnou jendotkou '),
    ('ExistenceAndOwnership', 5, N'finančné prostriedky sú vo vlastníctve účtovnéj jednotky '),
    ('ExistenceAndOwnership', 6, N'pohľadávky účtovnej jednotky  - odsúhlasené s účtovníctvom - bez zistených rozdielov'),
    ('ExistenceAndOwnership', 7, N'záväzky sa týkajú ekonomickej skutočnosti účtovnej jednotky - bez zistených rozdielov'),
    ('ExistenceAndOwnership', 8, N'rezervy sa týkajú ekonomickej skutočnosti účtovnej jednotky - bez zistených rozdielov'),
    ('ExistenceAndOwnership', 9, N'náklady budúcich období  sa týkajú nasledujúcich účtovných období účtovnej jednotky  - poistné sa vzťahuje na majetok v evidencii '),
    ('ExistenceAndOwnership', 10, N'zostatok  sa týka  účtovnej jednotky  '),
    ('ExistenceAndOwnership', 11, N'úver je evidovaný na účtovnú jednotku  - v priebehu obdobia nebol prijatý nový '),
    ('ExistenceAndOwnership', 12, N'náklady sa viažu na majetok v evidencii účtovnej jednotky'),
    ('ExistenceAndOwnership', 13, N'výnosy sa viažu na aktivity účtovnej jednotky -výnosy spojené s činnosťou účtovnej jednotky'),
    ('CompletenessOfAccounting', 1, N'všetky pohyby a zmeny boli zaúčtované'),
    ('CompletenessOfAccounting', 2, N'všetky pohyby sú zaúčtované v správnom období'),
    ('CompletenessOfAccounting', 3, N'všetky pohyby a zmeny boli zaúčtované '),
    ('CompletenessOfAccounting', 4, N'všetky pohyby a zmeny boli zaúčtované - priebežné účtovanie'),
    ('CompletenessOfAccounting', 5, N'všetky pohyby a zmeny boli zaúčtované - priebežné účtovanie fyzická kontrola, chaotický výber '),
    ('CompletenessOfAccounting', 6, N'všetky pohyby a zmeny boli zaúčtované - ročný predpis podľa pomocnej evidencie dcom'),
    ('CompletenessOfAccounting', 7, N'všetky pohyby a zmeny boli zaúčtované - kontrola nasledujúceho obdobia'),
    ('CompletenessOfAccounting', 8, N'všetky pohyby a zmeny boli zaúčtované - kontrola v nasledujúcom období '),
    ('CompletenessOfAccounting', 9, N'všetky pohyby a zmeny boli zaúčtované - všetky pohyby účtované bez zbytočného odkladu '),
    ('CompletenessOfAccounting', 10, N'všetky pohyby a zmeny boli zaúčtované - overenie predchádzajúcich 3 účtovných závierok - bez zistených nedostatkov'),
    ('CompletenessOfAccounting', 11, N'všetky pohyby a zmeny boli zaúčtované - úhrady istiny priebežne - krátkodobá časť na konci obdobia'),
    ('CompletenessOfAccounting', 12, N'všetky pohyby boli zaúčtované - kontrola obdobia 01/auditované obdobie - nezistené doklady viažúce sa na predchádzajúce obdobie'),
    ('CompletenessOfAccounting', 13, N'všetky pohyby boli zaúčtované '),
    ('AccuratePeriodDetermination', 1, N'všetky zmeny sú zaúčtované v správnom období'),
    ('AccuratePeriodDetermination', 2, N'všetky pohyby sú zaúčtované v správnom období'),
    ('AccuratePeriodDetermination', 3, N'všetky pohyby sú zaúčtované v správnom období'),
    ('AccuratePeriodDetermination', 4, N'všetky pohyby sú zaúčtované v správnom období - overované doklady 01 auditované obdobie a 01 nasledujúce obdobie - nezaznamenané nesprávne účtovanie '),
    ('AccuratePeriodDetermination', 5, N'všetky pohyby sú zaúčtované v správnom období - overované doklady - neboli zistené nesprávne určené obdobie'),
    ('AccuratePeriodDetermination', 6, N'všetky pohyby sú zaúčtované v správnom období - overované - bez zistených nedostatkov '),
    ('AccuratePeriodDetermination', 7, N'všetky pohyby sú zaúčtované v správnom období - overované v nasledujúcom období '),
    ('AccuratePeriodDetermination', 8, N'všetky pohyby sú zaúčtované v správnom období - zmeny budú overované v nasledujúcom období '),
    ('AccuratePeriodDetermination', 9, N'všetky pohyby sú zaúčtované v správnom období  - dodržaný akruálny princíp - drobné rozdiely spôsobené zaokrúlením (počty dní nepresnosť + - jeden deň)'),
    ('AccuratePeriodDetermination', 10, N'všetky pohyby sú zaúčtované v správnom období  - dodržaný akruálny princíp '),
    ('AccuratePeriodDetermination', 11, N'všetky pohyby sú zaúčtované v správnom období  - dodržaný akruálny princíp '),
    ('AccuratePeriodDetermination', 12, N'všetky pohyby sú zaúčtované v správnom období  - dodržaný akruálny princíp '),
    ('AccuratePeriodDetermination', 13, N' pohyby sú zaúčtované v správnom období  - dodržaný akruálny princíp ');

INSERT [Settings].[PredefinedTexts] ([UserId], [CategoryCode], [TextId], [TextSk], [SortOrder])
SELECT u.[Id], t.[CategoryCode], t.[TextId], t.[TextSk], t.[TextId]
FROM [Settings].[Users] AS u CROSS JOIN @Texts AS t
WHERE NOT EXISTS (SELECT 1 FROM [Settings].[PredefinedTexts] AS x
                  WHERE x.[UserId] = u.[Id] AND x.[CategoryCode] = t.[CategoryCode] AND x.[TextId] = t.[TextId]);

DECLARE @Defaults table ([CategoryCode] varchar(50), [Account] varchar(3), [TextId] int);
INSERT @Defaults VALUES
    ('Valuation', '021', 1),
    ('Valuation', '022', 1),
    ('Valuation', '023', 1),
    ('Valuation', '031', 1),
    ('Valuation', '042', 1),
    ('Valuation', '052', 1),
    ('Valuation', '061', 1),
    ('Valuation', '063', 1),
    ('Valuation', '081', 2),
    ('Valuation', '082', 2),
    ('Valuation', '083', 2),
    ('Valuation', '094', 3),
    ('Valuation', '112', 4),
    ('Valuation', '211', 5),
    ('Valuation', '221', 5),
    ('Valuation', '231', 11),
    ('Valuation', '261', 5),
    ('Valuation', '315', 6),
    ('Valuation', '318', 6),
    ('Valuation', '319', 6),
    ('Valuation', '321', 7),
    ('Valuation', '323', 8),
    ('Valuation', '324', 7),
    ('Valuation', '331', 7),
    ('Valuation', '336', 7),
    ('Valuation', '342', 7),
    ('Valuation', '351', 7),
    ('Valuation', '357', 7),
    ('Valuation', '372', 6),
    ('Valuation', '378', 6),
    ('Valuation', '379', 7),
    ('Valuation', '384', 9),
    ('Valuation', '428', 10),
    ('Valuation', '431', 10),
    ('Valuation', '461', 11),
    ('Valuation', '472', 7),
    ('Valuation', '479', 7),
    ('Valuation', '501', 12),
    ('Valuation', '502', 12),
    ('Valuation', '511', 12),
    ('Valuation', '512', 12),
    ('Valuation', '513', 12),
    ('Valuation', '518', 12),
    ('Valuation', '521', 12),
    ('Valuation', '524', 12),
    ('Valuation', '525', 12),
    ('Valuation', '527', 12),
    ('Valuation', '538', 12),
    ('Valuation', '548', 12),
    ('Valuation', '551', 12),
    ('Valuation', '562', 12),
    ('Valuation', '568', 12),
    ('Valuation', '584', 12),
    ('Valuation', '602', 13),
    ('Valuation', '632', 13),
    ('Valuation', '633', 13),
    ('Valuation', '645', 13),
    ('Valuation', '648', 13),
    ('Valuation', '653', 13),
    ('Valuation', '698', 13),
    ('Valuation', '699', 13),
    ('Valuation', '751', 1),
    ('Valuation', '799', 1),
    ('ExistenceAndOwnership', '021', 1),
    ('ExistenceAndOwnership', '022', 1),
    ('ExistenceAndOwnership', '023', 1),
    ('ExistenceAndOwnership', '031', 1),
    ('ExistenceAndOwnership', '042', 1),
    ('ExistenceAndOwnership', '052', 1),
    ('ExistenceAndOwnership', '061', 1),
    ('ExistenceAndOwnership', '063', 1),
    ('ExistenceAndOwnership', '081', 2),
    ('ExistenceAndOwnership', '082', 2),
    ('ExistenceAndOwnership', '083', 2),
    ('ExistenceAndOwnership', '094', 3),
    ('ExistenceAndOwnership', '112', 4),
    ('ExistenceAndOwnership', '211', 5),
    ('ExistenceAndOwnership', '221', 5),
    ('ExistenceAndOwnership', '231', 11),
    ('ExistenceAndOwnership', '261', 5),
    ('ExistenceAndOwnership', '315', 6),
    ('ExistenceAndOwnership', '318', 6),
    ('ExistenceAndOwnership', '319', 6),
    ('ExistenceAndOwnership', '321', 7),
    ('ExistenceAndOwnership', '323', 8),
    ('ExistenceAndOwnership', '324', 7),
    ('ExistenceAndOwnership', '331', 7),
    ('ExistenceAndOwnership', '336', 7),
    ('ExistenceAndOwnership', '342', 7),
    ('ExistenceAndOwnership', '351', 7),
    ('ExistenceAndOwnership', '357', 7),
    ('ExistenceAndOwnership', '372', 6),
    ('ExistenceAndOwnership', '378', 6),
    ('ExistenceAndOwnership', '379', 7),
    ('ExistenceAndOwnership', '384', 9),
    ('ExistenceAndOwnership', '428', 10),
    ('ExistenceAndOwnership', '431', 10),
    ('ExistenceAndOwnership', '461', 11),
    ('ExistenceAndOwnership', '472', 7),
    ('ExistenceAndOwnership', '479', 7),
    ('ExistenceAndOwnership', '501', 12),
    ('ExistenceAndOwnership', '502', 12),
    ('ExistenceAndOwnership', '511', 12),
    ('ExistenceAndOwnership', '512', 12),
    ('ExistenceAndOwnership', '513', 12),
    ('ExistenceAndOwnership', '518', 12),
    ('ExistenceAndOwnership', '521', 12),
    ('ExistenceAndOwnership', '524', 12),
    ('ExistenceAndOwnership', '525', 12),
    ('ExistenceAndOwnership', '527', 12),
    ('ExistenceAndOwnership', '538', 12),
    ('ExistenceAndOwnership', '548', 12),
    ('ExistenceAndOwnership', '551', 12),
    ('ExistenceAndOwnership', '562', 12),
    ('ExistenceAndOwnership', '568', 12),
    ('ExistenceAndOwnership', '584', 12),
    ('ExistenceAndOwnership', '602', 13),
    ('ExistenceAndOwnership', '632', 13),
    ('ExistenceAndOwnership', '633', 13),
    ('ExistenceAndOwnership', '645', 13),
    ('ExistenceAndOwnership', '648', 13),
    ('ExistenceAndOwnership', '653', 13),
    ('ExistenceAndOwnership', '698', 13),
    ('ExistenceAndOwnership', '699', 13),
    ('ExistenceAndOwnership', '751', 1),
    ('ExistenceAndOwnership', '799', 1),
    ('CompletenessOfAccounting', '021', 1),
    ('CompletenessOfAccounting', '022', 1),
    ('CompletenessOfAccounting', '023', 1),
    ('CompletenessOfAccounting', '031', 1),
    ('CompletenessOfAccounting', '042', 1),
    ('CompletenessOfAccounting', '052', 1),
    ('CompletenessOfAccounting', '061', 1),
    ('CompletenessOfAccounting', '063', 1),
    ('CompletenessOfAccounting', '081', 2),
    ('CompletenessOfAccounting', '082', 2),
    ('CompletenessOfAccounting', '083', 2),
    ('CompletenessOfAccounting', '094', 3),
    ('CompletenessOfAccounting', '112', 4),
    ('CompletenessOfAccounting', '211', 5),
    ('CompletenessOfAccounting', '221', 5),
    ('CompletenessOfAccounting', '231', 11),
    ('CompletenessOfAccounting', '261', 5),
    ('CompletenessOfAccounting', '315', 6),
    ('CompletenessOfAccounting', '318', 6),
    ('CompletenessOfAccounting', '319', 6),
    ('CompletenessOfAccounting', '321', 7),
    ('CompletenessOfAccounting', '323', 8),
    ('CompletenessOfAccounting', '324', 7),
    ('CompletenessOfAccounting', '331', 7),
    ('CompletenessOfAccounting', '336', 7),
    ('CompletenessOfAccounting', '342', 7),
    ('CompletenessOfAccounting', '351', 7),
    ('CompletenessOfAccounting', '357', 7),
    ('CompletenessOfAccounting', '372', 6),
    ('CompletenessOfAccounting', '378', 6),
    ('CompletenessOfAccounting', '379', 7),
    ('CompletenessOfAccounting', '384', 9),
    ('CompletenessOfAccounting', '428', 10),
    ('CompletenessOfAccounting', '431', 10),
    ('CompletenessOfAccounting', '461', 11),
    ('CompletenessOfAccounting', '472', 7),
    ('CompletenessOfAccounting', '479', 7),
    ('CompletenessOfAccounting', '501', 12),
    ('CompletenessOfAccounting', '502', 12),
    ('CompletenessOfAccounting', '511', 12),
    ('CompletenessOfAccounting', '512', 12),
    ('CompletenessOfAccounting', '513', 12),
    ('CompletenessOfAccounting', '518', 12),
    ('CompletenessOfAccounting', '521', 12),
    ('CompletenessOfAccounting', '524', 12),
    ('CompletenessOfAccounting', '525', 12),
    ('CompletenessOfAccounting', '527', 12),
    ('CompletenessOfAccounting', '538', 12),
    ('CompletenessOfAccounting', '548', 12),
    ('CompletenessOfAccounting', '551', 12),
    ('CompletenessOfAccounting', '562', 12),
    ('CompletenessOfAccounting', '568', 12),
    ('CompletenessOfAccounting', '584', 12),
    ('CompletenessOfAccounting', '602', 13),
    ('CompletenessOfAccounting', '632', 13),
    ('CompletenessOfAccounting', '633', 13),
    ('CompletenessOfAccounting', '645', 13),
    ('CompletenessOfAccounting', '648', 13),
    ('CompletenessOfAccounting', '653', 13),
    ('CompletenessOfAccounting', '698', 13),
    ('CompletenessOfAccounting', '699', 13),
    ('CompletenessOfAccounting', '751', 1),
    ('CompletenessOfAccounting', '799', 1),
    ('AccuratePeriodDetermination', '021', 1),
    ('AccuratePeriodDetermination', '022', 1),
    ('AccuratePeriodDetermination', '023', 1),
    ('AccuratePeriodDetermination', '031', 1),
    ('AccuratePeriodDetermination', '042', 1),
    ('AccuratePeriodDetermination', '052', 1),
    ('AccuratePeriodDetermination', '061', 1),
    ('AccuratePeriodDetermination', '063', 1),
    ('AccuratePeriodDetermination', '081', 2),
    ('AccuratePeriodDetermination', '082', 2),
    ('AccuratePeriodDetermination', '083', 2),
    ('AccuratePeriodDetermination', '094', 3),
    ('AccuratePeriodDetermination', '112', 4),
    ('AccuratePeriodDetermination', '211', 5),
    ('AccuratePeriodDetermination', '221', 5),
    ('AccuratePeriodDetermination', '231', 11),
    ('AccuratePeriodDetermination', '261', 5),
    ('AccuratePeriodDetermination', '315', 6),
    ('AccuratePeriodDetermination', '318', 6),
    ('AccuratePeriodDetermination', '319', 6),
    ('AccuratePeriodDetermination', '321', 7),
    ('AccuratePeriodDetermination', '323', 8),
    ('AccuratePeriodDetermination', '324', 7),
    ('AccuratePeriodDetermination', '331', 7),
    ('AccuratePeriodDetermination', '336', 7),
    ('AccuratePeriodDetermination', '342', 7),
    ('AccuratePeriodDetermination', '351', 7),
    ('AccuratePeriodDetermination', '357', 7),
    ('AccuratePeriodDetermination', '372', 6),
    ('AccuratePeriodDetermination', '378', 6),
    ('AccuratePeriodDetermination', '379', 7),
    ('AccuratePeriodDetermination', '384', 9),
    ('AccuratePeriodDetermination', '428', 10),
    ('AccuratePeriodDetermination', '431', 10),
    ('AccuratePeriodDetermination', '461', 11),
    ('AccuratePeriodDetermination', '472', 7),
    ('AccuratePeriodDetermination', '479', 7),
    ('AccuratePeriodDetermination', '501', 12),
    ('AccuratePeriodDetermination', '502', 12),
    ('AccuratePeriodDetermination', '511', 12),
    ('AccuratePeriodDetermination', '512', 12),
    ('AccuratePeriodDetermination', '513', 12),
    ('AccuratePeriodDetermination', '518', 12),
    ('AccuratePeriodDetermination', '521', 12),
    ('AccuratePeriodDetermination', '524', 12),
    ('AccuratePeriodDetermination', '525', 12),
    ('AccuratePeriodDetermination', '527', 12),
    ('AccuratePeriodDetermination', '538', 12),
    ('AccuratePeriodDetermination', '548', 12),
    ('AccuratePeriodDetermination', '551', 12),
    ('AccuratePeriodDetermination', '562', 12),
    ('AccuratePeriodDetermination', '568', 12),
    ('AccuratePeriodDetermination', '584', 12),
    ('AccuratePeriodDetermination', '602', 13),
    ('AccuratePeriodDetermination', '632', 13),
    ('AccuratePeriodDetermination', '633', 13),
    ('AccuratePeriodDetermination', '645', 13),
    ('AccuratePeriodDetermination', '648', 13),
    ('AccuratePeriodDetermination', '653', 13),
    ('AccuratePeriodDetermination', '698', 13),
    ('AccuratePeriodDetermination', '699', 13),
    ('AccuratePeriodDetermination', '751', 1),
    ('AccuratePeriodDetermination', '799', 1);

INSERT [Settings].[PredefinedTextMappings] ([UserId], [CategoryCode], [Account], [TextId])
SELECT u.[Id], d.[CategoryCode], d.[Account], d.[TextId]
FROM [Settings].[Users] AS u CROSS JOIN @Defaults AS d
JOIN [Settings].[PredefinedTexts] AS t
  ON t.[UserId] = u.[Id] AND t.[CategoryCode] = d.[CategoryCode] AND t.[TextId] = d.[TextId]
WHERE NOT EXISTS (SELECT 1 FROM [Settings].[PredefinedTextMappings] AS x
                  WHERE x.[UserId] = u.[Id] AND x.[CategoryCode] = d.[CategoryCode] AND x.[Account] = d.[Account]);
GO
