using ExcelApiPoc.AccountingImport.Services.Layouts;
using ExcelApiPoc.AccountingImport.Services.SoftipMop;
using ExcelApiPoc.AccountingImport.Models;
using PdfLayoutEngine.Simple;
namespace PdfLayoutEngine.SimpleTests;
public class SoftipMopLayoutTests
{
    static string Layouts=>Path.Combine(AppContext.BaseDirectory,"SoftipMop");
    static readonly string[] Header={"Účt.mes.","DD","Číslo dokladu","Účet","Dát.účt.","Popis zápisu","St.","DAL","Stredisko","Má dať"};
    static string[] Row(string period="202512",string date="31.12.2025",string debit="12.34",string credit="0",string account="02101")=>new[]{period,"VB","000123",account,date,"Description","state",credit,"100",debit};
    [Fact]public void Named_columns_preserve_sides_and_metadata(){
        var p=UrbisLayoutTests.Workbook(new[]{Header,Row(credit:"-1.23")});try{using var i=new CompactLayoutImporter(p,Layouts);var r=i.Examine(ImportLevel.Identify);Assert.Equal("softip-mop-excel-aj",r.LayoutId);Assert.Empty(r.Rows);Assert.Equal("2025",r.Identifiers["fiscalYear"]);Assert.Null(r.Identifiers["cin"]);Assert.Equal("completed",i.Examine(ImportLevel.Normalize).Status);var j=Assert.IsType<JournalImport>(i.Canonical);var row=Assert.Single(j.Rows);Assert.Equal("Softip-MOP",j.AccountingFormat);Assert.Equal("000123",row.DocumentNumber);Assert.Equal("VB",row.DocumentType);Assert.Equal("02101",row.DebitAccount);Assert.Equal("02101",row.CreditAccount);Assert.Equal(12.34m,row.DebitAmount);Assert.Equal(-1.23m,row.CreditAmount);Assert.Equal("100",row.DebitCostCenter);Assert.Equal("100",row.CreditCostCenter);}finally{File.Delete(p);}
    }
    [Theory,InlineData("01.01.2026"),InlineData("31.02.2025")]
    public void Accounting_year_controls_date_review(string date){var p=UrbisLayoutTests.Workbook(new[]{Header,Row(date:date)});try{using var i=new CompactLayoutImporter(p,Layouts);Assert.Equal("completed",i.Examine(ImportLevel.Normalize).Status);var j=Assert.IsType<JournalImport>(i.Canonical);Assert.Equal(2025,j.FiscalYear);Assert.False(Assert.Single(j.Rows).UsedForReportCalculation);}finally{File.Delete(p);}}
    [Fact]public void Zero_rows_stay_in_source_only(){var p=UrbisLayoutTests.Workbook(new[]{Header,Row(),Row(debit:"0")});try{using var i=new CompactLayoutImporter(p,Layouts);var r=i.Examine(ImportLevel.Normalize);Assert.Equal("completed",r.Status);Assert.Equal(2,r.Rows.Count);Assert.Single(r.Rows,x=>x.Kind=="ZeroPosting");Assert.Single(Assert.IsType<JournalImport>(i.Canonical).Rows);}finally{File.Delete(p);}}
    [Theory,InlineData("202513","12","02101","inconsistentAccountingPeriod"),InlineData("202511","12","02101","inconsistentAccountingPeriod"),InlineData("202512","bad","02101","invalidAmount"),InlineData("202512","12","bad","invalidAccount")]
    public void Invalid_rows_block_canonical(string period,string amount,string account,string code){var p=UrbisLayoutTests.Workbook(new[]{Header,Row(),Row(period:period,debit:amount,account:account)});try{using var i=new CompactLayoutImporter(p,Layouts);Assert.Contains(i.Examine(ImportLevel.Normalize).Issues,x=>x.Code==code);Assert.Null(i.Canonical);}finally{File.Delete(p);}}
    [Theory,InlineData(false),InlineData(true)]
    public void Missing_or_duplicate_amount_header_is_rejected(bool duplicate){var h=(string[])Header.Clone();h[9]=duplicate?"DAL":"other";var p=UrbisLayoutTests.Workbook(new[]{h,Row()});try{using var i=new CompactLayoutImporter(p,Layouts);Assert.Throws<InvalidDataException>(()=>i.Examine(ImportLevel.Normalize));}finally{File.Delete(p);}}
    [Fact]public void Monthly_merge_sorts_and_preserves_provenance(){var jan=UrbisLayoutTests.Workbook(new[]{Header,Row("202501","01.01.2025")});var feb=UrbisLayoutTests.Workbook(new[]{Header,Row("202502","01.02.2025")});try{var j=new SoftipMopMonthlyJournalImporter().Import(new[]{feb,jan},Layouts);Assert.Equal(2,j.Rows.Count);Assert.Equal(1,j.Rows[0].PostingDate.Month);Assert.Equal(2,j.Rows[1].SequenceNumber);Assert.Equal(Path.GetFileName(jan),j.Rows[0].SourceFields["SourceFile"]);Assert.True(j.Rows.All(x=>x.UsedForReportCalculation));Assert.Throws<InvalidDataException>(()=>new SoftipMopMonthlyJournalImporter().Import(new[]{jan,jan},Layouts));}finally{File.Delete(jan);File.Delete(feb);}}
    [Fact]public void Monthly_merge_rejects_mixed_years(){var a=UrbisLayoutTests.Workbook(new[]{Header,Row()});var b=UrbisLayoutTests.Workbook(new[]{Header,Row("202601","01.01.2026")});try{Assert.Throws<InvalidDataException>(()=>new SoftipMopMonthlyJournalImporter().Import(new[]{a,b},Layouts));}finally{File.Delete(a);File.Delete(b);}}
    [Fact]public void Six_pdf_definitions_load(){var files=Directory.GetFiles(Layouts,"pdf-*.json");Assert.Equal(6,files.Length);foreach(var p in files)Assert.Equal("Softip-MOP",CompactLayout.Load(p).Producer);}
    static CompactLayout SheetLayout()=>new(){Version=2,Id="sheet",Producer="Fixture",Category="AJ",ImportKinds=new[]{"Record"},Worksheet=new(){PageWidth=600,PageHeight=800,Panels=new(){new(){Headers=new(){["Period"]=20,["Date"]=160},Columns=new(){["AccountingPeriod"]=new[]{20d,100d},["Account"]=new[]{100d,160d},["Date"]=new[]{160d,300d}}},new(){Headers=new(){["Debit"]=20,["Credit"]=100},Columns=new(){["DebitAmount"]=new[]{20d,100d},["CreditAmount"]=new[]{100d,200d}}}}}};
    [Fact]public void L2_reads_only_first_panel_and_full_import_joins_pages(){using var source=new Panels();using var session=new CompactSession(source,new[]{SheetLayout()});var early=session.Examine(ImportLevel.Identify);Assert.Equal(1,early.DecodedPageCount);Assert.Empty(early.Rows);Assert.Equal("2025",early.Identifiers["fiscalYear"]);var r=session.Examine(ImportLevel.Validate);Assert.Equal("completed",r.Status);var row=Assert.Single(r.Rows);Assert.Equal("1,2",row.Fields["SourcePages"]);Assert.Equal(12.34m,row.Amounts["DebitAmount"]);Assert.Equal("02101",row.Fields["DebitAccount"]);}
    [Theory,InlineData("shift","panelRowMismatch"),InlineData("missing","missingAmount"),InlineData("header","panelHeaderMismatch"),InlineData("empty","criticalPageContentMissing")]
    public void Unsafe_panel_join_or_missing_amount_is_rejected(string fault,string code){using var source=new Panels(fault);using var session=new CompactSession(source,new[]{SheetLayout()});var r=session.Examine(ImportLevel.Validate);Assert.Equal("invalid",r.Status);Assert.Contains(r.Issues,x=>x.Code==code);}
    sealed class Panels:IPageSource{
        public string Format=>"fixture";public int PageCount=>2;readonly HashSet<int> read=new();public int DecodedPageCount=>read.Count;public PositionedDocument Document{get;}=new();
        public Panels(string fault=""){for(int i=0;i<2;i++)Document.Pages.Add(new(){WidthPt=600,HeightPt=800,PhysicalPageIndex=i});Put(0,"Period",20,750);Put(0,"Date",160,750);Put(0,"202512",20,730);Put(0,"02101",100,730);Put(0,"31.12.2025",160,730);Put(1,fault=="header"?"Wrong":"Debit",20,750);Put(1,"Credit",100,750);if(fault!="empty"){double y=fault=="shift"?720:730;Put(1,"12.34",20,y);if(fault!="missing")Put(1,"0.00",100,y);}}
        void Put(int p,string text,double x,double y){string run=Guid.NewGuid().ToString();foreach(char c in text){Document.Pages[p].Text.Add(new(){Text=c.ToString(),RunId=run,Baseline=new(x,y),AdvanceEnd=new(x+3,y),FontSize=8});x+=3;}}
        public PositionedPage ReadPage(int index,CancellationToken token=default){read.Add(index);return Document.Pages[index];}public void Dispose(){}
    }
    [Fact]public void Known_middle_panel_alternative_is_explicit(){using var source=new Panels("header");var layout=SheetLayout();var main=layout.Worksheet!.Panels[1];main.Alternatives.Add(new(){Headers=new(){["Wrong"]=20,["Credit"]=100},Columns=main.Columns});using var session=new CompactSession(source,new[]{layout});Assert.Equal("completed",session.Examine(ImportLevel.Validate).Status);}
    [Theory,InlineData(false),InlineData(true)]
    public void Subtotal_amounts_can_continue_after_repeated_page_header(bool omitAmounts){
        using var source=new SplitSubtotal(omitAmounts);var layout=new CompactLayout{Version=2,Id="gl",Category="GL",ImportKinds=new[]{"Record"},Table=new(){TitlePattern="^Ledger$",LeftLabel="Account",RightLabel="Amount",Left=20,Right=150,LastHeaderLabel="Amount",Columns=new(){["Account"]=new[]{20d,80d},["Structure"]=new[]{20d,150d},["SubtotalAccount"]=new[]{100d,150d},["PeriodTurnoverDebit"]=new[]{150d,240d}},Amounts=new[]{"PeriodTurnoverDebit"},Rules=new(){new(){Kind="Record",Field="Account",Pattern=@"^\d{5}$"},new(){Kind="SyntheticTotal",Field="Structure",Pattern="^Total"}},ContinueAcrossPages=true,ContinueAmountKinds=new[]{"SyntheticTotal"},AccountPattern=@"^\d{5}$",ControlMode="accountTotals",GroupPattern="(?!)"}};
        using var session=new CompactSession(source,new[]{layout});var r=session.Examine(ImportLevel.Validate);var total=Assert.Single(r.Rows,x=>x.Kind=="SyntheticTotal");if(omitAmounts){Assert.Equal("invalid",r.Status);Assert.Null(total.Amounts["PeriodTurnoverDebit"]);}else{Assert.True(r.Status=="completed",string.Join("; ",r.Issues.Select(x=>x.Code+": "+x.Message)));Assert.Equal(12.34m,total.Amounts["PeriodTurnoverDebit"]);Assert.Equal("2",total.Fields["AmountContinuationPage"]);}
    }
    sealed class SplitSubtotal:IPageSource{
        public string Format=>"fixture";public int PageCount=>2;public int DecodedPageCount=>2;public PositionedDocument Document{get;}=new();
        public SplitSubtotal(bool omit){for(int n=0;n<2;n++){Document.Pages.Add(new(){WidthPt=600,HeightPt=800,PhysicalPageIndex=n});Put(n,"Ledger",20,770);Put(n,"Strana : "+(n+1)+" / 2",400,750);Put(n,"Account",20,710);Put(n,"Amount",150,710);}Put(0,"02101",20,680);Put(0,"12.34",150,680);Put(0,"Total",20,660);Put(0,"021",100,660);if(!omit)Put(1,"12.34",150,680);}
        void Put(int p,string text,double x,double y){string run=Guid.NewGuid().ToString();foreach(char c in text){Document.Pages[p].Text.Add(new(){Text=c.ToString(),RunId=run,Baseline=new(x,y),AdvanceEnd=new(x+3,y),FontSize=8});x+=3;}}
        public PositionedPage ReadPage(int index,CancellationToken token=default)=>Document.Pages[index];public void Dispose(){}
    }
    static CompactLayout DynamicSheet(){var layout=SheetLayout();layout.Worksheet!.DynamicHeaders=true;layout.Worksheet.Panels[0].HeaderFields=new(){["AccountingPeriod"]="Period",["Account"]="Account",["Date"]="Date"};layout.Worksheet.Panels[1].HeaderFields=new(){["DebitAmount"]="Debit",["CreditAmount"]="Credit"};return layout;}
    [Fact]public void Independent_column_width_changes_use_actual_header_positions(){using var source=new DynamicPanels();using var session=new CompactSession(source,new[]{DynamicSheet()});var early=session.Examine(ImportLevel.Identify);Assert.Equal("completed",early.Status);Assert.Equal(2,early.DecodedPageCount);Assert.Empty(early.Rows);var r=session.Examine(ImportLevel.Validate);Assert.Equal("completed",r.Status);var row=Assert.Single(r.Rows);Assert.Equal("02101",row.Fields["Account"]);Assert.Equal("31.12.2025",row.Fields["Date"]);Assert.Equal(1234.56m,row.Amounts["DebitAmount"]);Assert.Equal(-12.34m,row.Amounts["CreditAmount"]);}
    [Theory,InlineData("unknown"),InlineData("missing"),InlineData("order")]
    public void Dynamic_recognition_requires_the_whole_panel_structure(string fault){using var source=new DynamicPanels(fault);using var session=new CompactSession(source,new[]{DynamicSheet()});var r=session.Examine(ImportLevel.Recognize);Assert.Null(r.LayoutId);Assert.Empty(r.Rows);}
    [Fact]public void Dynamic_layout_cannot_omit_header_mapping(){var layout=DynamicSheet();layout.Worksheet!.Panels[1].HeaderFields.Remove("CreditAmount");Assert.Throws<InvalidDataException>(()=>layout.Worksheet.Validate());}
    [Fact]public void Null_accounting_period_is_invalid(){Assert.False(SingleAccountJournal.Period(null,out _,out _));}
    sealed class DynamicPanels:IPageSource{
        public string Format=>"fixture";public int PageCount=>2;readonly HashSet<int> read=new();public int DecodedPageCount=>read.Count;public PositionedDocument Document{get;}=new();
        public DynamicPanels(string fault=""){for(int i=0;i<2;i++)Document.Pages.Add(new(){WidthPt=600,HeightPt=800,PhysicalPageIndex=i});Put(0,"Period",20,750);Put(0,"Account",115,750);Put(0,"Date",180,750);Put(0,"202512",20,730);Put(0,"02101",115,730);Put(0,"31.12.2025",180,730);Put(1,fault=="order"?"Credit":"Debit",20,750);if(fault!="missing")Put(1,fault=="order"?"Debit":"Credit",135,750);if(fault=="unknown")Put(1,"Other",240,750);Put(1,"1234.56",75,730);Put(1,"-12.34",160,730);}
        void Put(int p,string text,double x,double y){string run=Guid.NewGuid().ToString();foreach(char c in text){Document.Pages[p].Text.Add(new(){Text=c.ToString(),RunId=run,Baseline=new(x,y),AdvanceEnd=new(x+3,y),FontSize=8});x+=3;}}
        public PositionedPage ReadPage(int index,CancellationToken token=default){read.Add(index);return Document.Pages[index];}public void Dispose(){}
    }
}
