<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExcelDataReader" Version="3.9.0" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PdfLayoutEngine\PdfLayoutEngine.csproj" />
    <ProjectReference Include="..\PdfLayoutEngine.IText\PdfLayoutEngine.IText.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\PdfLayouts\SoftipMop\general-ledger.v1.json">
      <Link>PdfLayouts\SoftipMop\general-ledger.v1.json</Link>
      <LogicalName>ExcelApiPoc.AccountingImport.PdfLayouts.SoftipMop.general-ledger.v1.json</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\PdfLayouts\Ives\journal.v1.json">
      <Link>PdfLayouts\Ives\journal.v1.json</Link>
      <LogicalName>ExcelApiPoc.AccountingImport.PdfLayouts.Ives.journal.v1.json</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
