using System;

namespace ExcelApiPoc.AccountingImport.Services.MkSoft
{
    public sealed class MkSoftJournalSourceRow
    {
        public int SourceRowNumber { get; set; }

        // Document/header identity repeated by MkSoft on every movement row.
        public string DocumentId { get; set; }
        public string DocumentSequence { get; set; }
        public string DocumentType { get; set; }
        public string DocumentNumber { get; set; }
        public DateTime? PostingDate { get; set; }
        public DateTime? EvidenceDate { get; set; }
        public string Description { get; set; }
        public string CompanyId { get; set; }
        public string SpecialCode { get; set; }

        // Movement identity and accounting fields.
        public string MovementId { get; set; }
        public string MovementDocumentId { get; set; }
        public string MovementSequence { get; set; }
        public string DebitAccount { get; set; }
        public string CreditAccount { get; set; }
        public decimal? DebitAmount1 { get; set; }
        public decimal? CreditAmount1 { get; set; }
        public decimal? DebitAmount2 { get; set; }
        public decimal? CreditAmount2 { get; set; }
        public decimal? DebitAmount { get; set; }
        public decimal? CreditAmount { get; set; }
        public decimal? DebitForeignAmount { get; set; }
        public decimal? CreditForeignAmount { get; set; }
        public string DebitCurrency { get; set; }
        public string CreditCurrency { get; set; }
        public string DebitCostCenter { get; set; }
        public string CreditCostCenter { get; set; }
        public string DebitOrder { get; set; }
        public string CreditOrder { get; set; }
        public string DebitTurnoverCode { get; set; }
        public string CreditTurnoverCode { get; set; }
        public string MovementDescription { get; set; }
        public string AutoGenerated { get; set; }
    }
}
