<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PdfLayoutEngine/PdfLayoutEngine.csproj" />
    <ProjectReference Include="../PdfLayoutEngine.IText/PdfLayoutEngine.IText.csproj" />
    <ProjectReference Include="../PdfLayoutEngine.Xps/PdfLayoutEngine.Xps.csproj" />
  </ItemGroup>
</Project>
